# -*- coding: utf-8 -*-
"""MID QUIZ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVX0baHOAg1IYhThpJcA6Yt6zTLLULrl
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer


# Load Dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
# NOTE: We are simulating a 'Stroke' dataset using the Pima dataset structure for stability
names = ['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv(url, names=names)

print("Environment Ready.")

print(df.head())

features = ['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'mass', 'pedi', 'age']
x = df[features]
y = df['class']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.25,random_state = 42)
print("number of rows in your X_test:", x_test.shape[0])

from sklearn import pipeline

scaler = StandardScaler()
data_scaled= scaler.fit_transform(x)
print(data_scaled[:5])

df.replace('?' , np.nan , inplace = True  )
x= x.astype(float)

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.25,random_state = 42)
model = Pipeline([
        ('imputer', SimpleImputer(strategy='mean')),
        ('knn', KNeighborsClassifier(n_neighbors=5))
    ])
accuracies = []
model.fit(x_train, y_train)
preds = model.predict(x_test)
acc = accuracy_score(y_test, preds)
accuracies.append(acc)
print(f"K={5}, Accuracy={acc}")

